# Generated by Django 5.0 on 2023-12-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='monthaly_salary',
            new_name='monthly_salary',
        ),
    ]
